branch-defaults:
  acs:
    environment: centralbcs-dev
    group_suffix: null
  master:
    environment: centralbcs
    group_suffix: null
environment-defaults:
  centralbcs:
    branch: null
    repository: null
  agist-worker:
    branch: null
    repository: null
  centralbcs-dev:
    branch: null
global:
  application_name: centralbcs
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: python2.7
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
